### ISSUE TITLE
Functions Checklist

### ISSUE THREAD

**Issue by go-christianharrel** [PUPT-CaPro-2025/BioSync#149]
### Schedule
- [x] Create Schedule 
- [x] View Schedule
- [ ] Search Schedule
- [x] Edit Schedule
- [x] Delete Schedule

### Subjects
- [x] Add Subjects
- [x] View Subject
- [x] Edit Subjects 
- [x] Delete Subjetcs

### Professor
- [x] Add Professor
- [x] View Professor 
- [x] Edit Professors 
- [x] Delete Professors

### Students 
- [x] Add Students
- [x] View Students
- [x] Edit Students
- [x] Delete Students

### Section
- [x] Add Section
- [x] View Sections
- [ ] Search Sections
- [x] Edit Sections
- [x] Delete Sections

### School Year
- [x] Add School Year
- [x] View School Year
- [ ] Search School Year
- [x] Edit School Year
- [x] Delete School Year

### Program
- [x] Add Program
- [x] View Program
- [ ] Search Program
- [x] Edit Program
- [x] Delete Program

### Laboratory
- [x] Add Laboratory
- [x] View Laboratory
- [ ] Search Laboratory
- [x] Edit Laboratory
- [x] Delete Laboratory

### Visitor
- [x] Add Visitor 
- [x] View Visitor

### Reports
- [x] Attendance
- [x] Schedule List
- [x] Subject List
- [x] Section List
- [x] Student List
- [x] Professor List
