### ISSUE TITLE
Process Requirements Checklist - For Mock 3

### ISSUE THREAD

**Issue by go-christianharrel** [PUPT-CaPro-2025/BioSync#160]
## 1st Process: Maintenance/Admin Module
- [x] Program Management
- [x] Section Management
- [x] School Year Management
- [x] Laboratory Management
- [x] Professor Management
- [ ] Schedule Conflict Prompt

#### Expected Output:
- [x] Admin can create schedules

---

## 2nd Process: Faculty Module
- [x] Faculty Sign-In Module
- [x] Faculty can view their schedule
- [ ] Faculty can start attendance
- [ ] Faculty can view students assigned to a schedule

#### Expected Output:
- [ ] Faculty can view their schedule and start the attendance

---

## 3rd Process: Student Module
- [x] Sign-In Module
- [ ] Students can view their schedule
- [ ] Students can view their attendance
- [x] Visitor Module

#### Expected Outcome:
- [ ] Students must view their schedule and attendance

---

### Dashboards
- [x] Admin Dashboard
- [ ] Faculty Dashboard
- [ ] Student Dashboard

---

### Reports
- [ ] Schedule List Report
- [ ] Professor List Report
- [ ] Student List Report
- [ ] Laboratory List Report
- [ ] Program List Report
- [ ] School Year List Report
- [ ] Section List Report
- [ ] Subject List Report
- [ ] Visitor List Report

---

### To Work on After Mock 3
- **Professor**: Request make-up class or another schedule
- **Student**: Request attendance correction when the student was present but didn’t log their biometrics
- **Admin/Professor**: Add students to a schedule using CSV
  - Countercheck if the student is existing or registered
  - If not, their account will be put on hold
- Admin and Faculty: Auto login or auto start attendance when biometrics is triggered (no need to input credentials)
- Attendance using barcode system
- Implement validations across all modules
- API integration for student info, professor info, and scheduling
- **Professor**: Admin view of the calendar for professor schedules.
