### ISSUE TITLE
Process Requirements Checklist - For Mock 3

### ISSUE THREAD

**Issue by go-christianharrel** [PUPT-CaPro-2025/BioSync#164]
### Discussed in https://github.com/PUPT-CaPro-2025/BioSync/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **go-christianharrel** September 17, 2024</sup>
## 1st Process: Maintenance/Admin Module
- [x] Program Management
- [x] Section Management
- [x] School Year Management
- [x] Laboratory Management
- [x] Professor Management
- [x] Schedule Conflict Prompt

#### Expected Output:
- [x] Admin can create schedules

---

## 2nd Process: Faculty Module
- [x] Faculty Sign-In Module
- [x] Faculty can view their schedule
- [x] Faculty can start attendance
- [x] Faculty can view students assigned to a schedule

#### Expected Output:
- [x] Faculty can view their schedule and start the attendance

---

## 3rd Process: Student Module
- [x] Sign-In Module
- [x] Students can view their schedule
- [x] Students can view their attendance
- [x] Visitor Module

#### Expected Outcome:
- [x] Students must view their schedule and attendance

---

### Dashboards
- [x] Admin Dashboard
- [x] Faculty Dashboard
- [x] Student Dashboard

---

### Reports
- [x] Schedule List Report
- [x] Attendance Report
- [x] Professor List Report
- [x] Student List Report
- [x] Laboratory List Report
- [x] Program List Report
- [x] School Year List Report
- [x] Section List Report
- [x] Subject List Report
- [x] Visitor List Report

---

### To Work on After Mock 3
- **Professor**: Request make-up class or another schedule
- **Student**: Request attendance correction when the student was present but didn’t log their biometrics
- **Admin/Professor**: Add students to a schedule using CSV
  - Countercheck if the student is existing or registered
  - If not, their account will be put on hold
- Admin and Faculty: Auto login or auto start attendance when biometrics is triggered (no need to input credentials)
- Attendance using barcode system
- Implement validations across all modules
- API integration for student info, professor info, and scheduling
- **Professor**: Admin view of the calendar for professor schedules.
</div>

**Comment by go-christianharrel** [comment]
lofit @Galope-Jhean :rocket:

**Comment by Galope-Jhean** [comment]
closing this @go-christianharrel
