### ISSUE TITLE
Requirements Checklist

### ISSUE THREAD

**Issue by go-christianharrel** [PUPT-CaPro-2025/BioSync#242]
- [x] **Add Student via CSV**
     - Implement functionality to allow bulk student registration through CSV file upload.

- [x] **Student Request for Attendance**
     - Enable students to request attendance adjustments.
     - Send notification to both admin and respective professors upon a student's attendance request.

- [x] **Professor Request for Schedule**
     - Allow professors to submit requests for schedule adjustments.
     - Notify admin when a professor submits a schedule request.
     - Notify the professor once the admin responds to their request.

- [x] **Attendance Biometrics**
     - Implement facial recognition to record attendance for students and professors.
     - Add fingerprint recognition for attendance logging of students and professors.

- [x] **Attendance Violations**
     - Automatically mark students as "Late" if they arrive more than 15 minutes after the professor has started taking attendance.

- [x] **Reports**
     - Generate a schedule report in calendar format that can be sorted by laboratory.

**Comment by Galope-Jhean** [comment]
noted on this. thanks

**Comment by Galope-Jhean** [comment]
resolved
